# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

# Position Controllers ---------------------------------------
joint1:
  position_controller:
    type: position_controllers/JointPositionController
    joint: joint1
    pid: {p: 1.0, i: 0.01, d: 10.0}
joint2:
  position_controller:
    type: position_controllers/JointPositionController
    joint: joint2
    pid: {p: 1.0, i: 0.01, d: 10.0}
joint3:
  position_controller:
    type: position_controllers/JointPositionController
    joint: joint3
    pid: {p: 1.0, i: 0.01, d: 10.0}