# cartesian_:
sewing_start_point:
  x: 0.3    # m w.r.t cartesian physical zero [motor1's edge] [hw zero]
  y: 0.3    # m w.r.t cartesian physical zero [motor1's edge]
  z: -1.57  # rad
home_point:
  x: 0.2    # m w.r.t robot's working zero [sw zero]
  y: 0.3    # m w.r.t robot's working zero [sw zero]
  z: 1.57   # rad
gear_ratios:
  joint1: 0.01114
  joint2: 0.01114
  joint3: 13.33
needle:
  x: 0.6 #1.29    # m w.r.t cartesian physical zero [motor1's edge] [hw zero]
  y: 0.3 #0.3    # m w.r.t cartesian physical zero [motor1's edge] [hw zero]
offsets:
  x: 0.0    # m
  y: 0.0    # m
  z: 0.0    # m
third_link:
  radius: 0.0   # not needed for now!
  